# Endpoint paths observed in Swagger UI.pdf (v1 subset)
# Base URL: https://api.collegebasketballdata.com
ENDPOINTS = {
  "games": "/games",
  "games_media": "/games/media",
  "games_teams": "/games/teams",
  "games_players": "/games/players",
  "sub_game": "/substitutions/game/{gameId}",
  "sub_player": "/substitutions/player/{playerId}",
  "sub_team": "/substitutions/team",
  "plays_game": "/plays/game/{gameId}",
  "plays_player": "/plays/player/{playerId}",
  "plays_team": "/plays/team",
  "plays_date": "/plays/date",
  "plays_tournament": "/plays/tournament",
  "plays_types": "/plays/types",
  "teams": "/teams",
  "teams_roster": "/teams/roster",
  "conferences": "/conferences",
  "conferences_history": "/conferences/history",
  "venues": "/venues",
  "stats_team_season": "/stats/team/season",
  "stats_team_shooting_season": "/stats/team/shooting/season",
  "stats_player_season": "/stats/player/season",
  "stats_player_shooting_season": "/stats/player/shooting/season",
  "ratings_adjusted": "/ratings/adjusted",
  "ratings_srs": "/ratings/srs",
  "rankings": "/rankings",
  "lines": "/lines",
  "lines_providers": "/lines/providers",
  "lineups_game": "/lineups/game/{gameId}",
  "lineups_team": "/lineups/team",
  "recruiting_players": "/recruiting/players",
  "draft_picks": "/draft/picks",
  "draft_positions": "/draft/positions",
  "draft_teams": "/draft/teams",
}
